// Products hardcoded here appear on production even when the DB is empty.
// DB records take precedence — these are used only when a slug is missing from DB.
export const HARDCODED_PRODUCTS = [
  {
    id: -1,
    slug: 'banh-bong-lan-trung-muoi',
    nameVi: 'Bánh Bông Lan Trứng Muối',
    nameEn: 'Salted Egg Sponge Cake',
    shortDescriptionVi: 'Cốt bánh mềm mịn, trứng muối nướng bùi thơm, chà bông chuẩn, 4 loại sốt đặc biệt',
    shortDescriptionEn: 'Soft sponge cake, roasted salted egg, premium pork floss, 4 special sauces',
    descriptionVi: 'Bánh bông lan cốt mềm mịn, trứng muối nướng bùi thơm, chà bông chuẩn vị, 4 loại sốt đặc biệt. Đặt trước để không bỏ lỡ mẻ đầu tiên!',
    descriptionEn: 'Soft sponge cake with roasted salted egg, premium pork floss and 4 special sauces. Pre-order now to be first in line!',
    price: '40',
    displayPrice: '£40 / cái',
    images: ['https://static.bonucakes.com/products/banh-bong-lan-trung-muoi.jpg'],
    available: false,
    featured: true,
    promoTitle: 'Pre-Order',
    category: 'food',
    tags: ['cake', 'preorder'],
    stock: 0,
    stockStatus: 'out_of_stock',
    allergens: [] as string[],
    productVariants: [] as any[],
    nutritionInfo: null,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: -2,
    slug: 'cha-bong',
    nameVi: 'Chà Bông Heo',
    nameEn: 'Pork Floss',
    shortDescriptionVi: 'Chà bông heo tự làm, sợi bông tơi xốp, vị đậm vừa ăn. 500g: £35 | 1kg: £70',
    shortDescriptionEn: 'Homemade pork floss, light and fluffy, perfectly seasoned. 500g: £35 | 1kg: £70',
    descriptionVi: 'Chà bông heo làm thủ công theo công thức truyền thống. Sợi bông tơi xốp, vị đậm vừa ăn, phù hợp cho cả trẻ em và người lớn. Dùng kèm cơm, cháo, xôi, hoặc bánh mì.',
    descriptionEn: 'Handmade pork floss with a traditional recipe. Light and fluffy, perfectly balanced flavour for all ages. Great with rice, congee, sticky rice, or banh mi.',
    price: '35',
    displayPrice: '£35 / 500g | £70 / 1kg',
    images: ['/images/products/cha-bong-1.webp', '/images/products/cha-bong-2.webp'],
    available: true,
    featured: true,
    category: 'food',
    tags: ['floss', 'pork'],
    stock: 99,
    stockStatus: 'in_stock',
    allergens: [] as string[],
    productVariants: [] as any[],
    nutritionInfo: null,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];
