// Products hardcoded here appear on production even when the DB is empty.
// DB records take precedence — these are used only when a slug is missing from DB.
export const HARDCODED_PRODUCTS = [
  {
    id: -1,
    slug: 'banh-bong-lan-trung-muoi',
    nameVi: 'Bánh Bông Lan Trứng Muối',
    nameEn: 'Salted Egg Sponge Cake',
    shortDescriptionVi: 'Cốt bánh mềm mịn tan trong miệng, trứng muối nướng bùi thơm, chà bông chuẩn, 4 loại sốt đặc biệt của Bonu',
    shortDescriptionEn: 'Soft melt-in-mouth sponge cake, roasted salted egg, premium pork floss, 4 Bonu special sauces',
    descriptionVi: 'Bánh bông lan cốt mềm mịn tan trong miệng — cốt bánh được làm tươi mỗi ngày, không chất bảo quản. Trứng muối nướng thơm bùi, chà bông heo chuẩn vị tự làm, kết hợp cùng 4 loại sốt đặc biệt của Bonu. Đặt trước để không bỏ lỡ mẻ đầu tiên!',
    descriptionEn: 'Soft melt-in-mouth sponge cake — baked fresh daily with no preservatives. Roasted salted egg, homemade pork floss, and 4 Bonu special sauces. Pre-order now to be first in line!',
    price: '40',
    displayPrice: '£40 / cái',
    images: ['https://static.bonucakes.com/products/banh-bong-lan-trung-muoi.jpg'],
    available: false,
    featured: true,
    promoTitle: 'Pre-Order',
    promoButtonText: 'Đặt trước ngay',
    promoButtonTextEn: 'Pre-Order Now',
    promoButtonLink: '/preorderBLTM',
    category: 'food',
    tags: ['cake', 'preorder'],
    stock: 0,
    stockStatus: 'out_of_stock',
    allergens: ['Gluten', 'Eggs', 'Milk'] as string[],
    ingredientsVi: 'Cốt bánh bông lan: bột mì, trứng gà tươi, đường, bơ, sữa tươi\nNhân bánh: trứng muối nướng, chà bông heo tự làm\n4 loại sốt đặc biệt: sốt bơ, sốt pho mát, sốt mặn ngọt, sốt kem\nKhông chất bảo quản',
    ingredientsEn: 'Sponge cake: flour, fresh eggs, sugar, butter, fresh milk\nFilling: roasted salted egg, homemade pork floss\n4 special sauces: butter sauce, cheese sauce, sweet-salty sauce, cream sauce\nNo preservatives',
    howToUseVi: 'BẢO QUẢN:\n- Ăn trong ngày tốt nhất\n- Bảo quản tủ lạnh tối đa 2 ngày\n- Lấy ra ngoài 10–15 phút trước khi ăn để bánh về nhiệt độ phòng\n\nĂN KÈM:\n- Có thể hâm nhẹ trong lò vi sóng 15–20 giây nếu muốn ăn ấm\n- Không nên hâm quá lâu vì cốt bánh dễ bị khô',
    howToUseEn: 'STORAGE:\n- Best eaten on the day of delivery\n- Refrigerate for up to 2 days\n- Remove from fridge 10–15 minutes before eating\n\nSERVING:\n- Can microwave for 15–20 seconds for a warm cake\n- Do not overheat as the sponge may dry out',
    productVariants: [] as any[],
    productFaqs: [
      {
        id: -11,
        questionVi: 'Pre-order hoạt động như thế nào?',
        questionEn: 'How does pre-order work?',
        answerVi: 'Bạn điền form đặt trước, Bonu sẽ liên hệ trong 1–2 ngày để xác nhận ngày giao và thanh toán.',
        answerEn: 'You fill in the pre-order form, and Bonu will contact you within 1–2 days to confirm delivery and payment.',
      },
      {
        id: -12,
        questionVi: 'Bánh có thể đặt số lượng nhiều không?',
        questionEn: 'Can I order multiple cakes?',
        answerVi: 'Được, có thể đặt nhiều cái. Ghi số lượng vào phần ghi chú khi đặt trước.',
        answerEn: 'Yes, you can order multiple cakes. Just note the quantity in the pre-order form.',
      },
      {
        id: -13,
        questionVi: 'Giao hàng đến đâu?',
        questionEn: 'Where do you deliver?',
        answerVi: 'Bonu hiện giao hàng trong khu vực UK. Liên hệ Bonu để biết chi tiết khu vực và phí ship.',
        answerEn: 'Bonu currently delivers within the UK. Contact Bonu for delivery area details and shipping fees.',
      },
    ],
    nutritionInfo: null,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: -2,
    slug: 'cha-bong',
    nameVi: 'Chà Bông Heo',
    nameEn: 'Pork Floss',
    shortDescriptionVi: 'Chà bông heo tự làm theo công thức truyền thống — sợi bông tơi xốp, vị đậm vừa ăn, không chất bảo quản',
    shortDescriptionEn: 'Homemade pork floss with a traditional recipe — light and fluffy, perfectly seasoned, no preservatives',
    descriptionVi: 'Chà bông heo làm thủ công hoàn toàn theo công thức truyền thống của Bonu. Thịt heo tươi chọn lọc, được rim với gia vị tự nhiên — không màu, không chất bảo quản. Sợi bông tơi xốp, vị đậm vừa ăn, phù hợp cho cả trẻ em và người lớn.\n\nDùng kèm cơm trắng, cháo, xôi, hay nhân bánh mì — đều ngon.',
    descriptionEn: 'Fully handmade pork floss following Bonu\'s traditional recipe. Fresh selected pork, slow-cooked with natural seasonings — no colouring, no preservatives. Light and fluffy strands, perfectly balanced flavour for all ages.\n\nGreat with steamed rice, congee, sticky rice, or as a banh mi filling.',
    price: '35',
    displayPrice: '£35 / 500g | £70 / 1kg',
    images: ['/images/products/cha-bong-1.webp', '/images/products/cha-bong-2.webp'],
    available: true,
    featured: true,
    category: 'food',
    tags: ['floss', 'pork'],
    stock: 99,
    stockStatus: 'in_stock',
    allergens: [] as string[],
    ingredientsVi: 'Thịt heo tươi chọn lọc\nNước mắm, đường, muối\nSả, gừng (gia vị tự nhiên)\nKhông màu, không chất bảo quản',
    ingredientsEn: 'Fresh selected pork\nFish sauce, sugar, salt\nLemongrass, ginger (natural spices)\nNo artificial colouring, no preservatives',
    howToUseVi: 'DÙNG KÈM:\n- Cơm trắng, cháo trắng, xôi\n- Nhân bánh mì Sài Gòn\n- Rắc lên trứng chiên, mì, bún\n- Cuộn cùng cơm nắm cho trẻ em\n\nBẢO QUẢN:\n- Chưa mở: để nơi khô mát, tránh ánh nắng — dùng trong 3 tháng\n- Đã mở: đóng kín nắp, bảo quản tủ lạnh — dùng trong 4 tuần',
    howToUseEn: 'SERVING SUGGESTIONS:\n- Steamed rice, plain congee, sticky rice\n- Saigon banh mi filling\n- Sprinkle on fried eggs, noodles, or vermicelli\n- Roll with rice balls for kids\n\nSTORAGE:\n- Unopened: store in a cool dry place away from sunlight — use within 3 months\n- Opened: seal tightly and refrigerate — use within 4 weeks',
    productVariants: [
      { id: -21, nameVi: 'Nửa ký (500g)', nameEn: '500g (Half kg)', price: '35', stock: 99, available: true },
      { id: -22, nameVi: 'Một ký (1kg)', nameEn: '1kg', price: '70', stock: 99, available: true },
    ],
    productFaqs: [
      {
        id: -21,
        questionVi: 'Chà bông có chứa chất bảo quản không?',
        questionEn: 'Does the pork floss contain preservatives?',
        answerVi: 'Không. Chà bông Bonu làm thủ công từ thịt heo tươi và gia vị tự nhiên, hoàn toàn không chứa chất bảo quản hay màu nhân tạo.',
        answerEn: 'No. Bonu\'s pork floss is handmade from fresh pork and natural seasonings — no preservatives or artificial colouring.',
      },
      {
        id: -22,
        questionVi: 'Trẻ em có dùng được không?',
        questionEn: 'Is it suitable for children?',
        answerVi: 'Được. Chà bông Bonu không cay, vị nhẹ vừa ăn, phù hợp cho trẻ từ 1 tuổi trở lên.',
        answerEn: 'Yes. Bonu pork floss is mild and not spicy, suitable for children from 1 year old.',
      },
      {
        id: -23,
        questionVi: 'Giao hàng đến đâu?',
        questionEn: 'Where do you deliver?',
        answerVi: 'Bonu hiện giao hàng trong khu vực UK. Liên hệ Bonu qua Facebook hoặc email để biết chi tiết.',
        answerEn: 'Bonu currently delivers within the UK. Contact Bonu via Facebook or email for details.',
      },
    ],
    nutritionInfo: null,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];
